/*
    AUTHENTICATION
*/
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCEEDED = 'USER_REGISTER_SUCCEEDED';

/*
    COMPONENTS
*/
export const LEFT_NAV_CLOSE = 'LEFT_NAV_CLOSE';
export const LEFT_NAV_OPEN = 'LEFT_NAV_OPEN';

/*
    DATA
*/
export const CITIES_BY_COUNTRY_FETCH_FAILED = 'CITIES_BY_COUNTRY_FETCH_FAILED';
export const CITIES_BY_COUNTRY_FETCH_REQUEST = 'CITIES_BY_COUNTRY_FETCH_REQUEST';
export const CITIES_BY_COUNTRY_RECEIVED = 'CITIES_BY_COUNTRY_RECEIVED';

export const CITIES_FETCH_FAILED = 'CITIES_FETCH_FAILED';
export const CITIES_FETCH_REQUEST = 'CITIES_FETCH_REQUEST';
export const CITIES_INSERT_SUCCEEDED = 'CITIES_INSERT_SUCCEEDED';
export const CITIES_INSERT_FAILED = 'CITIES_INSERT_FAILED';
export const CITIES_RECEIVED = 'CITIES_RECEIVED';

export const COMMENTS_BY_TOUR_FETCH_FAILED = 'COMMENTS_BY_TOUR_FAILED';
export const COMMENTS_BY_TOUR_FETCH_REQUEST = 'COMMENTS_BY_TOUR_FETCH_REQUEST';
export const COMMENTS_BY_TOUR_RECEIVED = 'COMMENTS_BY_TOUR_RECEIVED';

export const COUNTRIES_FETCH_FAILED = 'COUNTRIES_FETCH_FAILED';
export const COUNTRIES_FETCH_REQUEST = 'COUNTRIES_FETCH_REQUEST';
export const COUNTRIES_RECEIVED = 'COUNTRIES_RECEIVED';

export const LOCATIONS_FETCH_FAILED = 'LOCATIONS_FETCH_FAILED';
export const LOCATIONS_FETCH_REQUEST = 'LOCATIONS_FETCH_REQUEST';
export const LOCATIONS_INSERT_FAILED = 'LOCATIONS_INSERT_FAILED';
export const LOCATIONS_INSERT_SUCCEEDED = 'LOCATIONS_INSERT_SUCCEEDED';
export const LOCATIONS_RECEIVED = 'LOCATIONS_RECEIVED';

export const TOUR_FETCH_FAILED = 'TOUR_FETCH_FAILED';
export const TOUR_FETCH_REQUEST = 'TOUR_FETCH_REQUEST';
export const TOUR_RECEIVED = 'TOUR_RECEIVED';

export const TOURS_FETCH_FAILED = 'TOURS_FETCH_FAILED';
export const TOURS_FETCH_REQUEST = 'TOURS_FETCH_REQUEST';
export const TOURS_INSERT_FAILED = 'TOURS_INSERT_FAILED';
export const TOURS_INSERT_SUCCEEDED = 'TOURS_INSERT_SUCCEEDED';
export const TOURS_RECEIVED = 'TOURS_RECEIVED';

export const SPECIFIC_TOURS_FETCH_FAILED = 'SPECIFIC_TOURS_FETCH_FAILED';
export const SPECIFIC_TOURS_FETCH_REQUEST = 'SPECIFIC_TOURS_FETCH_REQUEST';
export const SPECIFIC_TOURS_INSERT_FAILED = 'SPECIFIC_TOURS_INSERT_FAILED';
export const SPECIFIC_TOURS_INSERT_SUCCEEDED = 'SPECIFIC_TOURS_INSERT_SUCCEEDED';
export const SPECIFIC_TOURS_RECEIVED = 'SPECIFIC_TOURS_RECEIVED';

/* 
    UTILITIES
*/
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';
export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST'; 
export const FILE_UPLOAD_SUCCEEDED = 'FILE_UPLOAD_SUCCEEDED';

/* REVISE */
//export const TOURS_SUCCESS = 'TOURS_SUCCESS';
//export const TOUR_SUCCESS = 'TOUR_SUCCESS';
//export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';