export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';

export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';
export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';

export const INSERT_CITY_SUCCEEDED = 'INSERT_CITY_SUCCEEDED';
export const INSERT_CITY_FAILED = 'INSERT_CITY_FAILED';
export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_FAILED = 'FETCH_CITIES_FAILED';
export const RECEIVE_CITIES = 'RECEIVE_CITIES';
export const FETCH_CITIES_BY_COUNTRY_REQUEST = 'FETCH_CITIES_BY_COUNTRY_REQUEST';
export const FETCH_CITIES_BY_COUNTRY_FAILED = 'FETCH_CITIES_BY_COUNTRY_FAILED';
export const RECEIVE_CITIES_BY_COUNTRY = 'RECEIVE_CITIES_BY_COUNTRY';

export const FETCH_LOCATIONS_BY_CITY_REQUEST = 'FETCH_LOCATIONS_BY_CITY_REQUEST';
export const FETCH_LOCATIONS_BY_CITY_FAILED = 'FETCH_LOCATIONS_BY_CITY_FAILED';
export const RECEIVE_LOCATIONS_BY_CITY = 'RECEIVE_LOCATIONS_BY_CITY';
export const INSERT_LOCATION_SUCCEEDED = 'INSERT_LOCATION_SUCCEEDED';
export const INSERT_LOCATION_FAILED = 'INSERT_LOCATION_FAILED';

export const TOURS_SUCCESS = 'TOURS_SUCCESS';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';