export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';

export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
export const TOURS_SUCCESS = 'TOURS_SUCCESS';
export const TOUR_SUCCESS = 'TOUR_SUCCESS';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';